### ISSUE TITLE
Successfully bound to service but never got onServiceConnected callback

### ISSUE THREAD

**Issue by maheshwarLigade** [googlesamples/google-services#117]
The issue is that 
<b>Successfully bound to service but never got onServiceConnected callback</b>

I also added the google-services.json file and i also configure the service in manifest file.

**Comment by ianbarber** [comment]
Could you add a little more context - were you trying a sample, and if not, could you include some code that demonstrates the issue?

**Comment by maheshwarLigade** [comment]
I have resolved the issue. There is issue in the google services json file.

**Comment by kulinek** [comment]
What was the issue in the json. I just got google service json downloaded. I am getting the error stated above when my app proceeds to download (startResult returned =2 . Hint: I just updated to google play services 10.

In manifest I have:

`<service android:name=".downloader.MCDownloaderService"></service>`

Error happens after few seconds when I finish (I pretty much follow the sample provided on android site):

`		try {
			if (doesExpansionFileExists()) return false; 
	        Log.d(TAG, "OBB file not found. Will try to download.");
	        Intent notifierIntent = new Intent(configurationFragment.getActivity(), ConfigurationActivity.class);
	        //These flags apply to ConfigurationActivity. I will need same when starting AlbumActivity. See comments in transitionToAlbumActivity
            notifierIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP);
            PendingIntent pendingIntent = PendingIntent.getActivity(configurationFragment.getActivity(), 0, notifierIntent, PendingIntent.FLAG_UPDATE_CURRENT);

            // Start the download service (if required)
            int startResult = DownloaderClientMarshaller.startDownloadServiceIfRequired(configurationFragment.getActivity(), pendingIntent, MCDownloaderService.class);
            Log.d(TAG, "Download startResult="+startResult);
            // If download has started, initialize this activity to show download progress
            if (startResult!=DownloaderClientMarshaller.NO_DOWNLOAD_REQUIRED) {
                // This is where you do set up to display the download progress (next step)
            	Log.d(TAG,  "CreateStub & FragmentClient.show()");
                downloaderClientStub = DownloaderClientMarshaller.CreateStub(this, MCDownloaderService.class);
                FragmentClient.showDownloaderFragment(configurationFragment.getActivity());
}`

stack trace is:

`D/LVLDL:` Service Bound
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41beb2a0)
D/dalvikvm: GC_CONCURRENT freed 769K, 15% free 6456K/7559K, paused 3ms+2ms, total 33ms
W/GAv4: syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.IllegalArgumentException: contentView required: pkg=com.meditationcreator id=-908767821 notification=Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x2 kind=[null])
                      at android.os.Parcel.readException(Parcel.java:1429)
                      at android.os.Parcel.readException(Parcel.java:1379)
                      at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:295)
                      at android.app.NotificationManager.notify(NotificationManager.java:124)
                      at android.app.NotificationManager.notify(NotificationManager.java:103)
                      at com.google.android.vending.expansion.downloader.impl.DownloadNotification.onDownloadStateChanged(DownloadNotification.java:145)
                      at com.google.android.vending.expansion.downloader.impl.DownloaderService$LVLRunnable.run(DownloaderService.java:752)
                      at android.os.Handler.handleCallback(Handler.java:615)
                      at android.os.Handler.dispatchMessage(Handler.java:92)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:4745)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                      at dalvik.system.NativeStart.main(Native Method)
E/GAv4: Successfully bound to service but never got onServiceConnected callback`
