### ISSUE TITLE
getDisplayName() on a null object reference

### ISSUE THREAD

**Issue by prathviraj080** [googlesamples/google-services#16]
06-16 11:56:57.979    1337-1337/? I/SBar.MotoNetworkCtrlr﹕ refreshSignalCluster[1]: wifi: mWifiConnected=true Wifi=0x7f02012e=com.android.systemui:drawable/stat_sys_wifi_signal_2_fully Activity=0x00000000=( none ) Accessibility="Wifi two bars."
06-16 11:56:57.979    1337-1337/? I/SBar.MotoNetworkCtrlr﹕ onReceive: WifiManager.RSSI_CHANGED_ACTION Received
06-16 11:56:57.979  22461-22461/? W/linker﹕ libavcodec.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
06-16 11:56:57.980    1337-1337/? I/SBar.MotoNetworkCtrlr﹕ updateDataIcon[0]: mCurrentDataSubId=-1000 maps to: dataPhoneId:0 ( SubscriptionManager.getPhoneId returned -1000=0xfffffc18 )
06-16 11:56:57.980    1337-1337/? I/SBar.MotoNetworkCtrlr﹕ updateDataNetType[1]: phoneId1 is not DDS( =phoneId0 ) ! -- Set all data icons to off ( SubscriptionManager.getPhoneId returned -1000=0xfffffc18 )
06-16 11:56:57.980    1337-1337/? I/SBar.MotoNetworkCtrlr﹕ updateDataIcon[1]: mCurrentDataSubId=-1000 maps to: dataPhoneId:0 ( SubscriptionManager.getPhoneId returned -1000=0xfffffc18 )
06-16 11:56:58.029    1337-1337/? I/SBar.MotoNetworkCtrlr﹕ updateDataIcon[0]: mCurrentDataSubId=-1000 maps to: dataPhoneId:0 ( SubscriptionManager.getPhoneId returned -1000=0xfffffc18 )
06-16 11:56:58.031    1337-1337/? I/SBar.MotoNetworkCtrlr﹕ updateDataNetType[1]: phoneId1 is not DDS( =phoneId0 ) ! -- Set all data icons to off ( SubscriptionManager.getPhoneId returned -1000=0xfffffc18 )
06-16 11:56:58.031    1337-1337/? I/SBar.MotoNetworkCtrlr﹕ updateDataIcon[1]: mCurrentDataSubId=-1000 maps to: dataPhoneId:0 ( SubscriptionManager.getPhoneId returned -1000=0xfffffc18 )
06-16 11:56:58.407  21991-22006/? I/art﹕ Background sticky concurrent mark sweep GC freed 24171(1770KB) AllocSpace objects, 11(227KB) LOS objects, 15% free, 10MB/12MB, paused 6.055ms total 131.023ms
06-16 11:56:58.502  21991-22400/? W/ActivityThread﹕ ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());
06-16 11:56:58.946  21991-22400/? E/Volley﹕ [80556] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/plus/v1/people/me
06-16 11:56:59.107  21991-22412/? W/BaseAppContext﹕ Using Auth Proxy for data requests.
06-16 11:56:59.166  22292-22302/com.google.samples.quickstart.signin W/art﹕ Suspending all threads took: 22.829ms
06-16 11:56:59.212  22292-22292/com.google.samples.quickstart.signin D/MainActivity﹕ onConnected:null
06-16 11:56:59.229  22292-22292/com.google.samples.quickstart.signin D/AndroidRuntime﹕ Shutting down VM
06-16 11:56:59.259  22292-22292/com.google.samples.quickstart.signin E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.google.samples.quickstart.signin, PID: 22292
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.google.android.gms.plus.model.people.Person.getDisplayName()' on a null object reference
            at com.google.samples.quickstart.signin.MainActivity.updateUI(MainActivity.java:107)
            at com.google.samples.quickstart.signin.MainActivity.onConnected(MainActivity.java:173)
            at com.google.android.gms.internal.jm.f(Unknown Source)
            at com.google.android.gms.common.api.c.gJ(Unknown Source)
            at com.google.android.gms.common.api.c.d(Unknown Source)
            at com.google.android.gms.common.api.c$2.onConnected(Unknown Source)
            at com.google.android.gms.internal.jm.f(Unknown Source)
            at com.google.android.gms.internal.jm.dU(Unknown Source)
            at com.google.android.gms.internal.jl$h.b(Unknown Source)
            at com.google.android.gms.internal.jl$h.g(Unknown Source)
            at com.google.android.gms.internal.jl$b.hy(Unknown Source)
            at com.google.android.gms.internal.jl$a.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by prathviraj080** [comment]
Resolved! I had not enabled Google+ API in Google Console (https://console.developers.google.com/project)
