### ISSUE TITLE
Android GCM problem to get token id

### ISSUE THREAD

**Issue by ryosaebawon** [googlesamples/google-services#183]
Hi guys,

I tried the gcm quick start sample. It works fine when i try it on emulator android API 19.
But it doesn't work on my phone android API 15.
`String token = instanceID.getToken(getString(R.string.gcm_defaultSenderId),
                    GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);` throws that exception :
 
```
java.io.IOException: SERVICE_NOT_AVAILABLE
     at com.google.android.gms.iid.zzc.zzb(Unknown Source)
     at com.google.android.gms.iid.zzc.zza(Unknown Source)
     at com.google.android.gms.iid.InstanceID.zzc(Unknown Source)
     at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
     at com.netinf.gcm.RegistrationIntentService.onHandleIntent(RegistrationIntentService.java:43)
     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:137)
     at android.os.HandlerThread.run(HandlerThread.java:60)
```
Someone knows this problem ?

Thanks,
Sebastien

**Comment by kroikie** [comment]
Hi @ryosaebawon SERVICE_NOT_AVAILABLE could be a temporary error where your device is not receiving the response. How often are you able to reproduce this error?

**Comment by ryosaebawon** [comment]
Hi @kroikie i have this error every time when i try with my phone. The application works every time with the emulator and never with the phone. I dont know if it matters, but my phone has internet only with wifi

**Comment by kroikie** [comment]
Hi @ryosaebawon it does not look like this is a library issue. Could you report your issue via the "Send Feedback" button at this link:
https://developers.google.com/cloud-messaging/android/start

You can provide more detailed information there like device model/manufacturer and OS version etc.

**Comment by ryosaebawon** [comment]
Ok i will do that. Thank you for your help

**Comment by brenohq** [comment]
same issue here
