### ISSUE TITLE
SigninActivity.java can leak the ProgressDialog window

### ISSUE THREAD

**Issue by opus1269** [googlesamples/google-services#200]
The easiest way to verify is to open it and hit the back button right away.

This will fix it:

``` java
    @Override
    protected void onPause() {
        super.onPause();

        if(mProgressDialog != null) {
            mProgressDialog.dismiss();
            mProgressDialog = null;
        }
    }
```

Exception:

```
04-10 04:02:42.067 3374-3374/com.google.samples.quickstart.signin E/WindowManager: android.view.WindowLeaked: Activity com.google.samples.quickstart.signin.SignInActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{3e1e5317 G.E..... R.....ID 0,0-1026,348} that was originally added here
                                                                                       at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
                                                                                       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
                                                                                       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                                       at android.app.Dialog.show(Dialog.java:298)
                                                                                       at com.google.samples.quickstart.signin.SignInActivity.showProgressDialog(SignInActivity.java:184)
                                                                                       at com.google.samples.quickstart.signin.SignInActivity.onStart(SignInActivity.java:96)
                                                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
                                                                                       at android.app.Activity.performStart(Activity.java:6006)
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by samtstern** [comment]
Closing this issue due to age (it's been a while since the last update).  If you still want to discuss, feel free to re-open.
