### ISSUE TITLE
[GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION

### ISSUE THREAD

**Issue by mtrakal** [googlesamples/google-services#253]
### Step 1: Are you in the right place?

NO, I'm not, but it's really hard to contact google for bug reports which are not related to http://b.android.com/ ... :/
- For issues or feature requests related to the code **in this repository** file a Github issue.
- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
### Step 2: Describe your environment
- Device: Sony Xperia Z3 Compact, Nexus 5, Elephone P6000
- OS version: 6.0.1, 6.0.1, 5.0.1
- SDK version: 24? Maybe, have no idea what google use...
- [Android] Google Play Services version: 9.2.56 (436-124593566)
### Step 3: Describe the problem:

https://gist.github.com/mtrakal/6445a6ec5f6e98ea3bd1c1600862f7fa
#### Steps to reproduce:
1. Do nothing, just put your phone on desk
2. Open logcat to track app and select No filters in AS
3. See a lot of stuf from Google play services....
#### Observed Results:

A lot of time does not work sync, Hangouts never show notifications and a lot of next ****...
#### Expected Results:

No errors! And working authentication!
#### Relevant Code:

It's obfuscated, no idea...

http://stackoverflow.com/questions/35967017/gettoken-failed-status-bad-authentication-error-found-in-android-studio

**Comment by IgorB10** [comment]
+1

**Comment by samtstern** [comment]
@mtrakal what sort of problems is this causing for you?  Or are you just concerned about excess logging.

**Comment by mtrakal** [comment]
Hi @samtstern,

it was not possible to login over https://developers.google.com/identity/sign-in/android/start

callback was never returned, or something like that. It's 4 month ago... I really don't remeber it :(.

**Comment by samtstern** [comment]
It's been a really long time since this thread was updated so I am going to close it.  If you'd like to keep discussing just comment and I will re-open it.  I hope your issue has been resolved since then but if not we can definitely keep working on it!

**Comment by softwaredementor** [comment]
I am facing similar issue. No idea what triggered it.

03-12 00:49:06.153 3675-3966/? W/Auth: [GoogleAuthUtil] GoogleAuthUtil
03-12 00:49:06.153 3675-3966/? W/GLSActivity: dcn: BadAuthentication
                                                  at dby.a(:com.google.android.gms:1518)
                                                  at dbx.a(:com.google.android.gms:914)
                                                  at dbx.e(:com.google.android.gms:526)
                                                  at dbw.a(:com.google.android.gms:37)
                                                  at ddj.getAuthToken(:com.google.android.gms:181)
                                                  at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:214)
                                                  at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:113)
                                                  at android.os.Binder.execTransact(Binder.java:453)
03-12 00:49:06.157 18474-18519/? W/PlayCommon: [4657] com.google.android.play.a.g.a(1018): Deferring log upload because couldn't retrieve auth token
03-12 00:49:06.353 18474-18522/? I/PlayCommon: [4660] com.google.android.play.a.g.e(932): Preparing logs for uploading
03-12 00:49:06.404 3675-7947/? E/Auth: [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:-1999935000>, App: com.android.vending, Service: androidmarket
                                       dgn: Long live credential not available.
                                           at dgo.a(:com.google.android.gms:3101)

**Comment by gingsero** [comment]
Hi, I'm searching that issue. I inform you how I can resolve this error.

Check login identification in android device.(I have three ids)
Remove an identification which is unsynchronized.

That's it... This error was disappeared.
I hope you resolve.

**Comment by samtstern** [comment]
@joonhocho what sort of problems does this cause for you?

**Comment by joonhocho** [comment]
@samtstern Currently I haven't tested throughly how this error really affects my app, but this error comes on my Android logging monitor every 15 seconds or so.

**Comment by eleguni** [comment]
i use my phone as emulator when it was android 6 it didnt have any problem once i upgraded my android to 7  this message appears on logcat

**Comment by amit-bst** [comment]
I am still having this issue to a lot of my users with android nougat.

**Comment by visw227** [comment]
I'm still having this error React-native android trying to sync entries to calendar

**Comment by NitzDKoder** [comment]
09-06 19:44:07.135 E/Auth    ( 3088): [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:1491413085>, App: com.google.android.gm, Service: oauth2:https://mail.google.com/ https://www.googleapis.com/auth/gmail.ads https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/taskassist.readonly https://www.googleapis.com/auth/plus.contactphotos https://www.googleapis.com/auth/reminders https://www.googleapis.com/auth/gmail.full_access 
09-06 19:44:07.135 E/Auth    ( 3088): fzk: Long live credential not available.

**Client side Getting same error. Sender-ID**

2018-09-05 12:52:04.289 pid:29578 worker:2 error: Push Notification error : "SENDER_ID_MISMATCH" 

**App Server Side getting SENDER_ID_MISMATCH.**

**Comment by NitzDKoder** [comment]
In my case there was actual mismatch.. server was picking wrong data.. now its sorted..

**Comment by ten-skv** [comment]
I'm also facing same issue. +1

**Comment by VergilUa** [comment]
I'm getting same issue as described, resulting in a complete auth soft-lock.

`04-16 17:14:43.452: E/Auth(2920): [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:-1387990655>, App: com.google.android.gms, Service: oauth2:https://www.googleapis.com/auth/games
04-16 17:14:43.452: E/Auth(2920): qmw: Long live credential not available.
04-16 17:14:43.452: E/Auth(2920): 	at gyz.c(:com.google.android.gms@16089039@16.0.89 (100408-239467275):18)
04-16 17:14:43.452: E/Auth(2920): 	at gyz.a(:com.google.android.gms@16089039@16.0.89 (100408-239467275):12)
04-16 17:14:43.452: E/Auth(2920): 	at gyz.b(Unknown Source:0)
04-16 17:14:43.452: E/Auth(2920): 	at gxk.a(:com.google.android.gms@16089039@16.0.89 (100408-239467275):22)
04-16 17:14:43.452: E/Auth(2920): 	at isb.a(:com.google.android.gms@16089039@16.0.89 (100408-239467275):7)
04-16 17:14:43.452: E/Auth(2920): 	at isb.a(:com.google.android.gms@16089039@16.0.89 (100408-239467275):161)
04-16 17:14:43.452: E/Auth(2920): 	at irb.a(Unknown Source:2)
04-16 17:14:43.452: E/Auth(2920): 	at iqz.a(:com.google.android.gms@16089039@16.0.89 (100408-239467275):17)
04-16 17:14:43.452: E/Auth(2920): 	at iqz.a(:com.google.android.gms@16089039@16.0.89 (100408-239467275):7)
04-16 17:14:43.452: E/Auth(2920): 	at gtw.a(:com.google.android.gms@16089039@16.0.89 (100408-239467275):33)
04-16 17:14:43.452: E/Auth(2920): 	at gtw.a(:com.google.android.gms@16089039@16.0.89 (100408-239467275):81)
04-16 17:14:43.452: E/Auth(2920): 	at guf.a(:com.google.android.gms@16089039@16.0.89 (100408-239467275):3)
04-16 17:14:43.452: E/Auth(2920): 	at gue.a(:com.google.android.gms@16089039@16.0.89 (100408-239467275):2)
04-16 17:14:43.452: E/Auth(2920): 	at gue.c(:com.google.android.gms@16089039@16.0.89 (100408-239467275):6)
04-16 17:14:43.452: E/Auth(2920): 	at gud.a(:com.google.android.gms@16089039@16.0.89 (100408-239467275):1)
04-16 17:14:43.452: E/Auth(2920): 	at gwb.getAuthToken(:com.google.android.gms@16089039@16.0.89 (100408-239467275):9)
04-16 17:14:43.452: E/Auth(2920): 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:246)
04-16 17:14:43.452: E/Auth(2920): 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:114)
04-16 17:14:43.452: E/Auth(2920): 	at android.os.Binder.transact(Binder.java:667)
04-16 17:14:43.452: E/Auth(2920): 	at duz.onTransact(:com.google.android.gms@16089039@16.0.89 (100408-239467275):3)
04-16 17:14:43.452: E/Auth(2920): 	at android.os.Binder.execTransact(Binder.java:731)
`

This happens when user has signed out via PlayGamesPlatform.Instance.SignOut(), then restarts the game and tries to authenticate again.

Also, this doesn't happen on all devices, but when it happens - it happens each time.

**Comment by Erraoudy** [comment]
+1

**Comment by yangga** [comment]
+1

**Comment by RogerioDoCarmo** [comment]
+1

**Comment by thiagoicarros** [comment]
Same issue here

**Comment by spun-Chris** [comment]
+1

**Comment by jafar-jabr** [comment]
+1

**Comment by keyserjaya** [comment]
Same Issue here

**Comment by Merlinkoss** [comment]
Same issue

**Comment by FrSenpai** [comment]
+1

**Comment by manjunath-teachmint** [comment]
+1

**Comment by Sienna94** [comment]
+1

**Comment by programming-paradox** [comment]
Same issue app crashes on startup

**Comment by Sigurd922** [comment]
Same issue app crashes on startup.

**Environment**
Device: Samsung Note 9, SC_01L
OS version: Android 8.1.0
SDK version: 33
[Android] Google Play Services version: 38.0.34-21[0][PR] 574417783

**Crash Logs**
The attachment is crash logs of our app.
[SC-01L_crash_on_startup.zip](https://github.com/googlesamples/google-services/files/13160640/SC-01L_crash_on_startup.zip)

**Comment by trunghieuvn** [comment]
work well for me
I added scope to this code:
Befor: `_googleSignIn = GoogleSignIn();)`

after fixed:
```
 _googleSignIn = GoogleSignIn(scopes: [
      'openid',
      'email',
    ]);
```
    
    
my libraries:
```
  firebase_core: 3.4.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.1.3
```

**Comment by lukehutch** [comment]
> _googleSignIn = GoogleSignIn(scopes: [
>       'openid',
>       'email',
>     ]);

Google scopes are supposed to be URLs, according to Google's OAuth2 docs. This is what I use:

```dart
final googleSignIn = GoogleSignIn(
  scopes: [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
  ],
  forceCodeForRefreshToken: Platform.isAndroid,
);
```

The fundamental problem with this issue however is that any one of 10 separate problems could trigger the exception (scopes, SHA1 key mismatch, ...), and there is no info in the exception as to what actually went wrong.

**Comment by nadas00** [comment]
> work well for me I added scope to this code: Befor: `_googleSignIn = GoogleSignIn();)`
> 
> after fixed:
> 
> ```
>  _googleSignIn = GoogleSignIn(scopes: [
>       'openid',
>       'email',
>     ]);
> ```
> 
> my libraries:
> 
> ```
>   firebase_core: 3.4.0
>   firebase_auth: ^5.2.0
>   google_sign_in: ^6.1.3
> ```

I tried everything for a whole day. If the bundle ID matches, the support email is added, and the app icon is present, but you're still encountering an error, the solution is definitely to add the scope as shown in the example. Thank you.

**Comment by Nde-Dilan** [comment]
I recently ran into the same issue while developing my app. I started off in debug mode and, following the docs, I added the SHA-1 and SHA-256 keys to the Firebase project settings. Everything was working fine so far. But when I switched to the release version to see how my app behaves in that environment, I started encountering errors.

I tried a bunch of different solutions, including directly adding the key to Google Cloud 
![GCP interface to add restrictions to API keys](https://github.com/user-attachments/assets/51e485db-c260-46fa-bb30-efb9807d7885)
, but none of that worked. After some more troubleshooting, I decided to try adding the key back to Firebase's project settings. And to my surprise, that fixed the issue! Now, everything works as expected in both debug and release mode.
 
![Firebase project settings](https://github.com/user-attachments/assets/aca8d237-923f-4969-b167-8dccdfc21cba)
 As you can see I have 4 keys now(2 for debugging and 2 for release)

So, if you're facing similar issues, make sure you've added both SHA-1 and SHA-256 keys to Firebase's project settings. That might just do the trick!
