### ISSUE TITLE
Bad magic number for Bundle: 0xffff4f45

### ISSUE THREAD

**Issue by Ansh1234** [googlesamples/google-services#289]
### Step 2: Describe your environment

  * Device: Mostly happening on Xiaomi devices.
  * OS version: Mostly happening on OS versions 5.0 and 5.1
  * SDK version: 22
  * [Android] Google Play Services version: 9.0.2
  
### Step 3: Describe the problem: Google sign in is working fine across the majority of devices. But somehow, it is crashing in some of the  Xiaomi devices. We are not able to reproduce the issue locally but are getting crash results from Crashlytics.

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}: java.lang.IllegalStateException: Bad magic number for Bundle: 0xffff4f45
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2342)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
       at android.app.ActivityThread.access$800(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5290)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
Caused by java.lang.IllegalStateException: Bad magic number for Bundle: 0xffff4f45
       at android.os.Parcel.readException(Parcel.java:1554)
       at android.os.Parcel.readException(Parcel.java:1499)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2441)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1496)
       at android.app.Activity.startActivityForResult(Activity.java:3794)
       at android.app.Activity.startActivityForResult(Activity.java:3755)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
       at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.zza(Unknown Source)
       at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6039)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
       at android.app.ActivityThread.access$800(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5290)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by samtstern** [comment]
@Ansh1234 thanks for the report.  I have raised this with the team, I will see if they can figure out what's going on.

**Comment by samtstern** [comment]
@Ansh1234 also while we don't know for sure, this could be fixed by upgrading your Google Play Services SDK version to `10.0.1`.  `9.0.2` is a very old version.

**Comment by Wojtek1234** [comment]
on 10.0.1 it still occurs, Redmi Note 2

**Comment by markoslo** [comment]
Got the same crash report for Redmi Note 4, OS version 6.0, Google Play Services SDK 1.0.1

**Comment by samtstern** [comment]
Hi all.

It's been a long time since an update on this issue and our internal investigation didn't turn up anything.  The only thing I can suggest is updating to the latest SDK and seeing if the behavior improves.  If anyone comes up with more information please comment and we can continue discussing.
