### ISSUE TITLE
Google plus login failes on use of updated goolge play services version i.e. 11.0.2

### ISSUE THREAD

**Issue by sudarshanthite** [googlesamples/google-services#330]
Environment
  * Device: android 7.0 or more
  * OS version: Android Nougat or greater than nougat.
  * SDK version: Android API level 26 or grater than it.
  * [Android] Google Play Services version: com.google.android.gms:play-services-auth:11.0.2
  
Problem :
    Google plus login get failed when we uses the latest updated google play services version i.e. 11 and application gets crashed. following is the crash and error log.

The following is the crash
FATAL EXCEPTION: main
                                                                Process: com.chefd.tech, PID: 22511
                                                                java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Lcom/google/android/gms/common/api/Api$zza;Lcom/google/android/gms/common/api/Api$zzc;)V in class Lcom/google/android/gms/common/api/Api; or its super classes (declaration of 'com.google.android.gms.common.api.Api' appears in /data/app/com.chefd.tech-1/base.apk:classes41.dex)
                                                                    at com.google.android.gms.plus.Plus.<clinit>(Unknown Source)
                                                                    at com.sa.sociallogin.login.GooglePlusLoginActivity.buidNewGoogleApiClient(GooglePlusLoginActivity.java:239)
                                                                    at com.sa.sociallogin.login.GooglePlusLoginActivity.onCreate(GooglePlusLoginActivity.java:183)
                                                                    at android.app.Activity.performCreate(Activity.java:6672)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by aaronj1335** [comment]
/cc @isaisachen

Do you have multidex enabled on this app?

**Comment by aaronj1335** [comment]
(based on `/data/app/com.chefd.tech-1/base.apk:classes41.dex` I'm going to assume that multidex is enabled).

Does setting `preDexLibraries = false` address the issue?

**Comment by samtstern** [comment]
@sudarshanthite can you show your entire `dependencies` block from your `app/build.gradle` file?  That will help to debug.

**Comment by isaisachen** [comment]
Yeah, please share your build.gradle dependencies configuration. One possibility is mixed versions of Play services SDK?

BTW, Plus.API has been deprecated for long:
https://developers.google.com/android/reference/com/google/android/gms/plus/Plus

We strongly recommend you to migrate to latest Google Sign-In API to get better UX and security benefits:
https://developers.google.com/identity/sign-in/android/sign-in
https://android-developers.googleblog.com/2016/05/improving-security-and-user-experience.html

**Comment by sudarshanthite** [comment]
In my project i was using the Plus.API for google login with the google play services version 11.0.2, When i used the Google Sign-IN API for google login with the google play services version 11.0.2 then it worked

Thanks.
