### ISSUE TITLE
Android SignIn returning cancelled code

### ISSUE THREAD

**Issue by neoacevedo** [googlesamples/google-services#394]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.

Maybe I'm in the right place. I searched for it in StackOverflow and nothing works.

### Step 2: Describe your environment

  * Device: Android Emulator / Nokia 6 / Motorola Moto G 2nd Gen
  * OS version: Android 6 (Motorola & Emulator) / Nokia 6 (Android One 8.1.0)
  * SDK version: 28.0.3
  * [Android] Google Play Services version: 16.0.1
  
### Step 3: Describe the problem:

On sign in with any Google account, it returns status 16 (cancelled)

#### Steps to reproduce:

 Nothing special, only following the official guide: https://developers.google.com/identity/sign-in/android/sign-in and downloading, compiling the sample in the repository and testing in above devices.
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
Before show the accounts, the log gets the following:
```
5289-5289/com.google.android.gms.ui I/AppCompatDelegate: Failed to instantiate custom view inflater android.support.v7.app.AppCompatViewInflater. Falling back to default.
    java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:324)
        at java.lang.Class.forName(Class.java:285)
        at android.support.v7.app.AppCompatDelegateImpl.a(:com.google.android.gms@13280022@13.2.80 (040700-211705629):1)
        at android.support.v7.app.AppCompatDelegateImpl.onCreateView(:com.google.android.gms@13280022@13.2.80 (040700-211705629):1)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3909)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969)
        at android.support.v7.app.AppCompatDelegateImpl.n(:com.google.android.gms@13280022@13.2.80 (040700-211705629):8)
        at android.support.v7.app.AppCompatDelegateImpl.h(:com.google.android.gms@13280022@13.2.80 (040700-211705629))
        at dip.onPostCreate(:com.google.android.gms@13280022@13.2.80 (040700-211705629))
        at com.google.android.chimera.Activity.publicOnPostCreate(:com.google.android.gms@13280022@13.2.80 (040700-211705629))
        at diu.onPostCreate(:com.google.android.gms@13280022@13.2.80 (040700-211705629):3)
        at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1188)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2398)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatViewInflater" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk"],nativeLibraryDirectories=[/data/user/0/com.google.android.gms/app_extracted_libs/x86, /system/priv-app/PrebuiltGmsCore/lib/x86, /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:324) 
        at java.lang.Class.forName(Class.java:285) 
        at android.support.v7.app.AppCompatDelegateImpl.a(:com.google.android.gms@13280022@13.2.80 (040700-211705629):1) 
        at android.support.v7.app.AppCompatDelegateImpl.onCreateView(:com.google.android.gms@13280022@13.2.80 (040700-211705629):1) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3909) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969) 
        at android.support.v7.app.AppCompatDelegateImpl.n(:com.google.android.gms@13280022@13.2.80 (040700-211705629):8) 
        at android.support.v7.app.AppCompatDelegateImpl.h(:com.google.android.gms@13280022@13.2.80 (040700-211705629)) 
        at dip.onPostCreate(:com.google.android.gms@13280022@13.2.80 (040700-211705629)) 
        at com.google.android.chimera.Activity.publicOnPostCreate(:com.google.android.gms@13280022@13.2.80 (040700-211705629)) 
        at diu.onPostCreate(:com.google.android.gms@13280022@13.2.80 (040700-211705629):3) 
        at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1188) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2398) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    	Suppressed: java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 30 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
private void signIn() {
    Intent signInIntent = mGoogleSignInClient.getSignInIntent();
    startActivityForResult(signInIntent, RC_SIGN_IN);
}

public void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);

    // Result returned from launching the Intent from GoogleSignInClient.getSignInIntent(...);
    if (requestCode == RC_SIGN_IN) {
        // The Task returned from this call is always completed, no need to attach
        // a listener.
        Task<GoogleSignInAccount> task = GoogleSignIn.getSignedInAccountFromIntent(data);
        handleSignInResult(task);
    }
}

private void handleSignInResult(Task<GoogleSignInAccount> completedTask) {
    try {
        GoogleSignInAccount account = completedTask.getResult(ApiException.class);

        // Signed in successfully, show authenticated UI.
        Log.w(TAG, "Email: "  + account.getEmail());
    } catch (ApiException e) {
        // The ApiException status code indicates the detailed failure reason.
        // Please refer to the GoogleSignInStatusCodes class reference for more information.
        Log.w(TAG, "signInResult:failed code=" + e.getStatusCode());
    }
}

  ```

**Comment by jorge-acosta-abstracta** [comment]
Hi, were you able to find the root cause of this issue ? I'm facing the same issue on my app.
