### ISSUE TITLE
Google Sign-In Quickstart not working

### ISSUE THREAD

**Issue by sonnyjon** [googlesamples/google-services#402]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.

### Step 2: Describe your environment

  * Device: Pixel 2
  * OS version: Android 9
  * SDK version: 27
  * [Android] Google Play Services version: 4.0.1
  
### Step 3: Describe the problem:

Attempted to run the sample signin-app. Google Sign-In Quickstart activity appears. Upon pressing the "G Sign In" button, screen flickers and nothing happens.

#### Steps to reproduce:

  1. Build and run signin-app from Android Studio using Pixel 2 as device.
  2. Press "Sign In" button on Quickstart activity.
  3. Select Google account to use.
  4. Wait for an eternity for nothing to happen.
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.

  Checking errors in the logcat shows:

2019-02-25 09:25:09.152 31865-31918/? E/bvzg: *~*~*~ Channel {0} was not shutdown properly!!! ~*~*~*
        Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
    java.lang.RuntimeException: ManagedChannel allocation site
        at bvzh.<init>(:com.google.android.gms@15090037@15.0.90 (100400-231259764):1)
        at bvzg.<init>(:com.google.android.gms@15090037@15.0.90 (100400-231259764):2)
        at bvzg.<init>(:com.google.android.gms@15090037@15.0.90 (100400-231259764):1)
        at bvry.b(:com.google.android.gms@15090037@15.0.90 (100400-231259764):13)
        at rfz.a(:com.google.android.gms@15090037@15.0.90 (100400-231259764):39)
        at rfz.a(:com.google.android.gms@15090037@15.0.90 (100400-231259764):60)
        at com.google.android.gms.signin.activity.SignInChimeraActivity.b(:com.google.android.gms@15090037@15.0.90 (100400-231259764):38)
        at aoss.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at rnb.run(:com.google.android.gms@15090037@15.0.90 (100400-231259764):21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at rsw.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)

#### Expected Results:

  * What did you expect to happen?

Something indicating a successful login or practically anything else other than nothing.
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by sonnyjon** [comment]
Nevermind, I didn't follow Step 2 "Configure a Google API project" before running the project yet. Will see if that fixes the issue.

**Comment by sonnyjon** [comment]
Step 2 was the key.
