### ISSUE TITLE
signin sample stuck on ApiException 12500

### ISSUE THREAD

**Issue by sgserg** [googlesamples/google-services#427]
### Step 2: Describe your environment

Nothing changed in the checked-out project besides web_client_ID

  * Device: emulator & Samsung Tab A tablet
  * OS version: _5.1.1_
  * SDK version: __27__
  * [Android] Google Play Services version: _17.0.0_
  
### Step 3: Describe the problem:
Problems with account, project and web client ID are ruled out: same details work fine on iOS.

On android, log on in any activity of the signin sample results in ApiException 12500, e.g.

> W/SignInActivity: signInResult:failed code=12500 unknown status code: 12500
    com.google.android.gms.common.api.ApiException: 12500: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(Unknown Source)
        at com.google.samples.quickstart.signin.SignInActivity.onActivityResult(SignInActivity.java:92)
        at android.app.Activity.dispatchActivityResult(Activity.java:6192)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
        at android.app.ActivityThread.access$1300(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

#### Steps to reproduce:

  1. __checkout signin sample app___
  2. __set up a project with web client ID___
  3. __run the app and perform any activity___
  
#### Observed Results:

ApiException 12500

**Comment by samtstern** [comment]
@sgserg this error code is hard to debug but please double-check some things:

1. You have the correct SHA1 listed in the developer console.
2. Your devices and emulators have the latest version of Google Play services installed.

Some more information here:
https://stackoverflow.com/questions/47632035/google-sign-in-error-12500

I would suggest using StackOverflow for future questions on this.

**Comment by sgserg** [comment]
@samtstern If I'm running just the SignInActivity, does any OAuth key need to be created?
The activity code doesn't reference any keys.

**Comment by samtstern** [comment]
Using Google Sign In requires a registered OAuth key in the developer console.

**Comment by sgserg** [comment]
Should "Web application" key be enough, when running the Android samples?

**Comment by sgserg** [comment]
My bad, [integration page](https://developers.google.com/identity/sign-in/android/start-integrating) clearly states SHA1 is a requirement.

**Comment by samtstern** [comment]
Please follow this guide:
https://developers.google.com/identity/sign-in/android/start-integrating
