### ISSUE TITLE
com.google.android.gms.common.api.ApiException: 8: 8:

### ISSUE THREAD

**Issue by LuigiSetola** [googlesamples/google-services#448]
### Step 1: Describe your environment

  * Device: Pixel 3 API 29 - Android Studio Emulator
  * OS version: Android 10.0 x86
  
### Step 3: Describe the problem:
When I open the app the logcat give me this:
```
E/Error: signInError
    com.google.android.gms.common.api.ApiException: 8: 8: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)
        at com.google.android.gms.common.internal.zai.zaf(com.google.android.gms:play-services-base@@17.1.0:2)
        at com.google.android.gms.common.internal.zak.onComplete(com.google.android.gms:play-services-base@@17.1.0:6)
        at com.google.android.gms.common.api.internal.BasePendingResult.zaa(com.google.android.gms:play-services-base@@17.1.0:176)
        at com.google.android.gms.common.api.internal.BasePendingResult.setResult(com.google.android.gms:play-services-base@@17.1.0:135)
        at com.google.android.gms.auth.api.signin.internal.zzi.zzc(com.google.android.gms:play-services-auth@@18.0.0:5)
        at com.google.android.gms.auth.api.signin.internal.zzs.dispatchTransaction(com.google.android.gms:play-services-auth@@18.0.0:6)
        at com.google.android.gms.internal.auth-api.zzc.onTransact(com.google.android.gms:play-services-auth@@18.0.0:13)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```
 
#### Expected Results:

  I expected that if I open the application, the GoogleSignInClient starts
  
#### Relevant Code:

  ```
  fun initGoogleClientAndSignin() {
        googleSignInClient = GoogleSignIn.getClient(
            this, GoogleSignInOptions.Builder(
                GoogleSignInOptions.DEFAULT_GAMES_SIGN_IN
            ).build()
        )

        googleSignInClient?.silentSignIn()?.addOnCompleteListener { task ->
            if (task.isSuccessful) {
                achievementClient = Games.getAchievementsClient(
                    this,
                    task.result!!
                )
                leaderboardsClient = Games.getLeaderboardsClient(
                    this,
                    task.result!!
                )
            } else {
                Log.e("Error", "signInError", task.exception)
            }
        }


    }
  ```

**Comment by sayantan300** [comment]
Who are you?

**Comment by absarahmad1995** [comment]
did u get the answer for it because I am getting the same error.

**Comment by ItzcoR** [comment]
I had this problem, In my case it was solved by changing `<meta-data` android:name="com.google.android.gms.games.APP_ID"
           android:value="<myAppID>" /> `
to 
`<meta-data android:name="com.google.android.gms.games.APP_ID"
           android:value="@string/app_id" />`
inside my main/AndroidManifest.xml file
