### ISSUE TITLE
android crash  by  implementation 'com.google.android.gms:play-services-auth:20.7.0'

### ISSUE THREAD

**Issue by billdizl** [googlesamples/google-services#602]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{xxx.xx.xx/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7838)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

 implementation 'com.google.android.gms:play-services-auth:20.7.0'
   classpath 'com.google.gms:google-services:4.4.0'

**Comment by billdizl** [comment]
have this  problem

**Comment by efstathiosntonas** [comment]
any updates on this one? getting tons of crashes

**Comment by pistolcaffe** [comment]
I also received this issue recently. The reproduction path is unclear, making it difficult to analyze the cause.

**Comment by rajatsharma16** [comment]
https://github.com/firebase/firebase-android-sdk/issues/5768
Updating `com.google.android.gms:play-services-auth` may help. Refer: https://developers.google.com/android/guides/setup
