### ISSUE TITLE
analytics debug problem - wont compile - google su...s

### ISSUE THREAD

**Issue by c3ph3us** [googlesamples/google-services#79]
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v13/app/FragmentCompat23;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

i'v tried but no result 

    compile('com.google.android.gms:play-services-analytics:8.1.0') {
        exclude group: 'com.google.android', module: 'support-v4'
        exclude group: 'com.google.android', module: 'support-v13'
        exclude module: 'support-v4'
        exclude module: 'support-v13'
        exclude module: 'appcompat-v7'
        exclude group: 'com.android.support'
        exclude group: 'com.android.support', module:'support-v4'
        exclude group: 'com.android.support', module:'support-v13'
        exclude group: 'com.android.support', module:'appcompat-v7'
    }

why gradle plugin not handling this ? 

i use 

studio 1.4 &
        classpath 'com.android.tools.build:gradle:1.3.1'
        classpath 'com.google.gms:google-services:1.4.0-beta4'

& my  ( 

    compile('com.android.support:support-v13:23.0.1') {
        force = true;
    }
    compile('com.android.support:appcompat-v7:23.0.1') {
        force = true;
    }
    compile 'org.jetbrains:annotations:13.0'
    compile 'com.android.support:design:23.0.1'
    compile 'com.android.support:recyclerview-v7:23.0.1'
    compile 'com.android.support:cardview-v7:23.0.1'
    compile 'com.android.support:palette-v7:23.0.1'

**Comment by samtstern** [comment]
@c3ph3us it looks like you have pretty heavily changed the original `build.gradle` file from this repository, so I cannot help you debug this.  If you restore the original `build.gradle` files,  **Clean** and then **Rebuild** your project, and still see this issue I can help you from there.

**Comment by c3ph3us** [comment]
what u mean by "restore the original build.gradle files"

**Comment by c3ph3us** [comment]
i'v added only code thats need to be ad to use analytics :
 
including this line in app gradle 
         apply plugin: 'com.google.gms.google-services'
         compile 'com.google.android.gms:play-services-analytics:8.1.0'

adding to top   level gradle   
        classpath 'com.android.tools.build:gradle:1.3.1'
        classpath 'com.google.gms:google-services:1.4.0-beta4'

results in - can't compile project 

         UNEXPECTED TOP-LEVEL EXCEPTION:
         com.android.dex.DexException: Multiple dex files define      Landroid/support/v13/app/FragmentCompat23;
         at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
         at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
         at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
         at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
         at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
         at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
         at com.android.dx.command.dexer.Main.run(Main.java:277)
         at com.android.dx.command.dexer.Main.main(Main.java:245)
         at com.android.dx.command.Main.main(Main.java:106)
